version: 0.9.1.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: MarkdownLog.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: MarkdownLog\bin\Release\MarkdownLog.dll
    name: MarkdownLog.dll
  - path: '**\*.nupkg'

#Temporarily commented out the Nuget package deploy. This should only be done on a separate non-dev branch
#deploy:
#  provider: NuGet
#  api_key:
#    secure: n/2gZwCGLcoLBr5nGu5akS0IFQ1YHciI6Wz0NGC+1mLTUtO08Uy+TWn7OtyLG9v3
#  artifact: /.*\.nupkg/
  
  
  