version: 0.9.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: MarkdownLog.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: MarkdownLog\bin\Release\MarkdownLog.dll
    name: MarkdownLog.dll
  - path: '**\*.nupkg'
  
deploy:
  provider: NuGet
  api_key:
    secure: ENi1LLqWdOQCPcy9s7wN+7MEIsJjfw6+IF6bFDOp/Dg=
  artifact: /.*\.nupkg/
  
  
  